const data = {
    products:[
        {
            _id:'1',
            name: 'MK18',
            category: 'Rifles',
            image:'./images/product-1.jpg',
            price: 120,
            brand :'Tokyo Marui',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'HK416',
            category: 'Rifles',
            image:'./images/product-2.jpg',
            price: 130,
            brand :'Tokyo Marui',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'AK47',
            category: 'Rifles',
            image:'./images/product-3.jpg',
            price: 90,
            brand :'Tokyo Marui',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'G36',
            category: 'Rifles',
            image:'./images/product-4.jpg',
            price: 140,
            brand :'Tokyo Marui',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'M16',
            category: 'Rifles',
            image:'./images/product-5.jpg',
            price: 110,
            brand :'Tokyo Marui',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
}; export default data;